name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
    - name: run
      run: |
        npm install
        npm run mirror
        git status
    - name: Open PR
      uses: peter-evans/create-pull-request@v3
      with:
        title: Automatic Update
