name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: run
      run: |
        npm ci
        npm run mirror
        git status
    - name: Open PR
      uses: peter-evans/create-pull-request@v4
      with:
        title: Automatic Update
